// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorshipConsole.Database;

#nullable disable

namespace Corona.Pageant.Migrations
{
    [DbContext(typeof(PageantDb))]
    [Migration("20260403180445_RemoveCameraPositions")]
    partial class RemoveCameraPositions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("WorshipConsole.Models.CameraInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfPresets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PanSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TiltSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UniFiPortNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ViscaPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ZoomSpeed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cameras");
                });

            modelBuilder.Entity("WorshipConsole.Models.PageantCameraPreset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CameraId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PresetNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PageantCameraPresets");
                });

            modelBuilder.Entity("WorshipConsole.Models.PageantObsScene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObsSceneName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PageantObsScenes");
                });

            modelBuilder.Entity("WorshipConsole.Models.Script", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Act")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Camera1Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Camera2Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Camera3Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Camera4Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseLights")
                        .HasColumnType("TEXT");

                    b.Property<string>("LightingNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scene")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SceneLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpotlightLeft")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotlightRight")
                        .HasColumnType("TEXT");

                    b.Property<string>("StageLightScene")
                        .HasColumnType("TEXT");

                    b.Property<string>("SwitchToScene")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Scripts");
                });

            modelBuilder.Entity("WorshipConsole.Models.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Setting")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
